In [2]:
import numpy as np

In [3]:
ar1=np.array(2)

In [4]:
ar1

array(2)

In [5]:
type(ar1)

numpy.ndarray

In [6]:
arr2=np.array([[2,4,6],[2,3,4]])

In [7]:

arr2

array([[2, 4, 6],
       [2, 3, 4]])

In [8]:

zero_array=np.zeros([4,2])

In [9]:
zero_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
ar4=np.arange(6)

In [11]:
ar4

array([0, 1, 2, 3, 4, 5])

In [12]:
ar4=np.transpose([[2,3,4],[5,6,7],[4,5,3]])

In [13]:
ar4

array([[2, 5, 4],
       [3, 6, 5],
       [4, 7, 3]])

In [14]:
ar4=np.transpose(arr2)

In [15]:
ar4

array([[2, 2],
       [4, 3],
       [6, 4]])

In [16]:
a1=np.array([2,2])
a2=np.array([4,5])

In [17]:
a1

array([2, 2])

In [18]:
a2

array([4, 5])

In [19]:
concat=np.concatenate((a1,a2))

In [20]:
concat

array([2, 2, 4, 5])

In [21]:
hori=np.hstack((a1,a2))

In [22]:
hori

array([2, 2, 4, 5])

In [23]:
veri=np.vstack((a1,a2))

In [24]:
veri

array([[2, 2],
       [4, 5]])

In [39]:
mat1=np.array([[2,3,4],[4,7,9],[5,5,7]])

In [40]:
mat1

array([[2, 3, 4],
       [4, 7, 9],
       [5, 5, 7]])

In [41]:
det_of_mat1=np.linalg.det(mat1)


In [42]:
det_of_mat1

-0.9999999999999964

In [43]:
inverse=np.linalg.inv(mat1)


In [44]:
inverse

array([[ -4.,   1.,   1.],
       [-17.,   6.,   2.],
       [ 15.,  -5.,  -2.]])

In [45]:
dense=np.array([[1,0,0,0],[1,2,0,0],[2,0,0,1],[2,0,0,0]])

In [46]:
dense

array([[1, 0, 0, 0],
       [1, 2, 0, 0],
       [2, 0, 0, 1],
       [2, 0, 0, 0]])

In [48]:
from scipy.sparse import csr_matrix

In [49]:
sparse=csr_matrix(dense)

In [50]:
sparse

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 6 stored elements in Compressed Sparse Row format>

In [51]:
print(sparse)

  (0, 0)	1
  (1, 0)	1
  (1, 1)	2
  (2, 0)	2
  (2, 3)	1
  (3, 0)	2
